---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Introduction
```{r eval=FALSE}
data.raw <- get.raw.dataset()
data.melt <- get.melted.dataset(data.raw)

data.melt$education_discrepancy <- data.melt$education_boys - data.melt$education_girls

data.melt %<>% append.regions()

write.csv(data.melt, "ComprehensiveMeltedData.csv", row.names=F)
```


```{r include=FALSE}
data.melt <- read.csv("ComprehensiveMeltedData.csv") %>%
  tibble::as_tibble() %>%
  dplyr::mutate_if(is.character, as.factor)

data.melt.avg <- data.melt %>% 
  dplyr::select(-"year") %>% 
  dplyr::group_by_if(is.factor) %>% dplyr::summarise_each(list(avg = ~mean(.x, na.rm=T)))

data.melt.standardized <- data.melt %>% 
  dplyr::mutate_if(is.numeric, function(x) (x-mean(x, na.rm=T))/sd(x, na.rm=T))
data.melt.standardized$year <- data.melt$year

region.color <- RColorBrewer::brewer.pal(8, "Set1")
```


```{r giniavg, fig.cap="Average Gini Coefficient", echo=FALSE}
world.regions <- establish.regions(levels(data.melt$country))
data.map(world.regions, "gini_avg", palette="RdYlBu", reverse.palette=T, domain.stretch=F)
```
